[variables]
JDK_VERSION = "17"

[phases.setup]
commands = [
    "curl -L -o java17.tar.gz https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz",
    "tar -xzf java17.tar.gz",
    "mkdir -p /opt/java17",
    "mv jdk-17*/ /opt/java17/"
]

[phases.build]
environment = { JAVA_HOME = "/opt/java17" }

[phases.start]
environment = { JAVA_HOME = "/opt/java17" }
