spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/certistage?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

qnet:
  base-url: https://apis.data.go.kr/B490007/qualExamSchd/getQualExamSchdList
  service-key: ${CERTI_API_KEY}
